apiVersion: apps/v1
kind: Deployment
metadata:
  name: forum-app-db-deployment
  labels:
    app: forum-app-db
spec:
  replicas: 2
  selector:
    matchLabels:
      app: database
  template:
    metadata:
      labels:
        app: database
    spec:
      containers:
      - name: database
        image: alerajo/forum-app-postgres-db:latest
        ports:
        - containerPort: 5432